version: "3.8"

services:
  db:
    image: mongo:latest
    restart: always
    container_name: "mongo-shorty"
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongo-vol:/data/db

  api:
    build: .
    restart: always
    container_name: "go-shorty"
    networks:
      - backend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    restart: always
    container_name: "redis-shorty"
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  mongo-vol:

networks:
  backend:
    driver: bridge
